Appearance settings explanation
hotspotty/documentation pull request #22
Opened 2022-01-15 16:47 UTC by bigredcorgi

main change appearance cog and filter description in understand your area. Rest are style tweaks.

2022-01-15 17:09 UTC, mugoosse requested changes

2022-01-15 17:09 UTC, mugoosse commented on docs/getting-started/understand-your-area-and-account-verification.md
> +Every dot on the map represents a hotspot as it is asserted in the Helium network. The chosen apperance settings filter dictates the color of the hotspots. The color of the dot corresponds with the h
There is a distinction between `hotspots` and `locations` on the map.

2022-01-15 17:09 UTC, mugoosse commented on docs/getting-started/understand-your-area-and-account-verification.md
> +Every dot on the map represents a hotspot as it is asserted in the Helium network. The chosen apperance settings filter dictates the color of the hotspots. The color of the dot corresponds with the h
`filtering` ->  the `relative performance` section doesn't really filter out anything. It just allows the user to specify based on what the hotspot  dots will be colored. Some of these metrics are absolute (e.g. online  =  green, offline = red), whereas others represent the relative performance of a metric of choice amongst  all hotspots in your area (purple zone). The histogram displays the meaning of each color and specifies the boundaries  of values  as well as how many fall under each 'bucket'.

2022-01-15 17:09 UTC, mugoosse commented on docs/getting-started/understand-your-area-and-account-verification.md
> +If you navigate to the appearance settings cog in the top right corner you can read more about the different filters at the bottom of the page.
see above

2022-01-15 17:09 UTC, mugoosse commented on docs/getting-started/understand-your-area-and-account-verification.md
> +If you want a detailed understanding of the hotspots' reward scale and how you can improve your reward potential see [Optimize your earnings and reward scaling](../expand-the-network/optimize-your-ea
Maybe refer to it as `reward scaling` and not `hotspot  reward scale` because there is no such thing. There are multiple concepts that are combined to `scale` the rewards,  for example `transmit scale` (HIP17) and `witness reward units` (HIP15). A simplified version of the latter is included in Hotspotty. More explanation can be found in the `PoC rewards explained` section of the `reward scaling` tab of a hotspot details page in Hotspotty.

2022-01-30 15:26 UTC, DevJelle commented on docs/getting-started/understand-your-area-and-account-verification.md
> +In the below example, we're filtering by witness reward units.
Done by Nadia.

2022-01-30 15:31 UTC, DevJelle commented on docs/getting-started/understand-your-area-and-account-verification.md
> +If you navigate to the appearance settings cog in the top right corner you can read more about the different filters at the bottom of the page.
Done by me.

2022-01-30 15:39 UTC, DevJelle commented on docs/getting-started/understand-your-area-and-account-verification.md
> +Every dot on the map represents a hotspot as it is asserted in the Helium network. The chosen apperance settings filter dictates the color of the hotspots. The color of the dot corresponds with the h
Done by Nadia.

2022-01-30 15:42 UTC, DevJelle commented on docs/getting-started/understand-your-area-and-account-verification.md
> +If you want a detailed understanding of the hotspots' reward scale and how you can improve your reward potential see [Optimize your earnings and reward scaling](../expand-the-network/optimize-your-ea
Done by me.

2022-01-30 16:13 UTC, merged